steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/nodeapp', '.']
images: ['gcr.io/$PROJECT_ID/nodeapp']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-rf', '/web.*', 'gs://cloudbuild-mm/web.tgz']
